package com.tencent.liteav.basic.datareport;

public class TXCDRDef
{
  public static int COMMAND_ID_40000;
  public static int COMMAND_ID_40001;
  public static int COMMAND_ID_40002;
  public static int COMMAND_ID_40003;
  public static int COMMAND_ID_40100;
  public static int COMMAND_ID_40101;
  public static int COMMAND_ID_40102;
  public static int COMMAND_ID_40200;
  public static int COMMAND_ID_40201;
  public static int COMMAND_ID_40202;
  public static String COMMAND_ID_COMMENT_DAU_49999;
  public static String COMMAND_ID_COMMENT_UGC_UPLOAD_40401;
  public static int COMMAND_ID_DAU;
  public static int COMMAND_ID_LINKMIC;
  public static int COMMAND_ID_UGC_UPLOAD;
  public static int COMMAND_ID_VOD_ACTION_DR;
  public static int DR_DAU_EVENT_ID_AVROOM_ENTER = 1301;
  public static int DR_DAU_EVENT_ID_BGM;
  public static int DR_DAU_EVENT_ID_EYE_SCALE;
  public static int DR_DAU_EVENT_ID_FACE_SCALE;
  public static int DR_DAU_EVENT_ID_FILTER;
  public static int DR_DAU_EVENT_ID_GREEN_SCREEN;
  public static int DR_DAU_EVENT_ID_LINK_MIC;
  public static int DR_DAU_EVENT_ID_LIVE_PLAY;
  public static int DR_DAU_EVENT_ID_LIVE_PUSH;
  public static int DR_DAU_EVENT_ID_MOTION_TMPL;
  public static int DR_DAU_EVENT_ID_REVERB;
  public static int DR_DAU_EVENT_ID_SCREEN_CAPTURE;
  public static int DR_DAU_EVENT_ID_UGC_CUT;
  public static int DR_DAU_EVENT_ID_UGC_JOIN;
  public static int DR_DAU_EVENT_ID_UGC_PLAY_RECORD;
  public static int DR_DAU_EVENT_ID_UGC_PUBLISH;
  public static int DR_DAU_EVENT_ID_UGC_PUSH_RECORD;
  public static int DR_DAU_EVENT_ID_VOD_PLAY;
  public static String DR_KEY_APP_ID;
  public static String DR_KEY_APP_NAME;
  public static String DR_KEY_APP_VER;
  public static String DR_KEY_BIZ_ID;
  public static String DR_KEY_DAU_ERR_CODE;
  public static String DR_KEY_DAU_ERR_INFO;
  public static String DR_KEY_DAU_EXT;
  public static String DR_KEY_DAU_MODULE_ID;
  public static String DR_KEY_DEV_ID;
  public static String DR_KEY_DEV_TYPE;
  public static String DR_KEY_DEV_UUID;
  public static String DR_KEY_ERROR_CODE;
  public static String DR_KEY_ERROR_MSG;
  public static String DR_KEY_EVT_COMM;
  public static String DR_KEY_MAC_ADDR;
  public static String DR_KEY_MODULE_ID = "u32_module_id";
  public static String DR_KEY_MSG_MORE;
  public static String DR_KEY_NET_TYPE;
  public static String DR_KEY_PLATFORM;
  public static String DR_KEY_STREAMURL = "str_stream_url";
  public static String DR_KEY_SYS_VER;
  public static String DR_KEY_UPLAOD_ERR_CODE;
  public static String DR_KEY_UPLAOD_ERR_INFO;
  public static String DR_KEY_UPLAOD_EVENT_ID;
  public static String DR_KEY_UPLOAD_FILE_SIZE;
  public static String DR_KEY_UPLOAD_UP_USE_TIME;
  public static String DR_KEY_UPLOAD_UP_ip;
  public static int DR_SDK_ID_RTMPSDK = 1;
  public static int MODULE_CDN;
  public static int MODULE_CONTROLLER;
  public static int MODULE_DC;
  public static int MODULE_LIVE_CODEC;
  public static int MODULE_PLAYER_SDK;
  public static int MODULE_PPSERVER;
  public static int MODULE_PUSH_SDK;
  public static int MODULE_STREAM_PROCESS;
  public static int MODULE_TEG_UPLOAD;
  public static int MODULE_UPLOAD;
  public static int MODULE_VOD_ACTION_PLAYER_SDK;
  public static int MODULE_VOD_PLAYER_SDK;
  public static int PEE_CONN_SERVER_FAILED;
  public static int PEE_DROP_FRAME;
  public static int PEE_ENCODE_FAIL;
  public static int PEE_ENCODE_FAIL_ANDROID;
  public static int PEE_ENCODE_INIT;
  public static int PEE_ENCODE_INIT_ANDROID;
  public static int PEE_QOS_RESULT;
  public static int PEE_QUIC_TO_TCP;
  public static int PEE_RECONN_BEGIN;
  public static int PEE_SERVER_DROP;
  public static int PEE_TURN_HWENCODE;
  public static int PEE_VIDEO_ENCODE_SW_TO_HW;
  public static int UPLOAD_EVENT_ID_REQUEST_UPLOAD = 1;
  public static int UPLOAD_EVENT_ID_UPLOAD = 2;
  public static int UPLOAD_EVENT_ID_UPLOAD_RESULT = 3;
  
  static
  {
    DR_KEY_PLATFORM = "platform";
    DR_KEY_BIZ_ID = "biz_id";
    DR_KEY_APP_ID = "app_id";
    DR_KEY_DEV_TYPE = "dev_type";
    DR_KEY_NET_TYPE = "net_type";
    DR_KEY_DEV_ID = "dev_id";
    DR_KEY_DEV_UUID = "dev_uuid";
    DR_KEY_APP_NAME = "app_name";
    DR_KEY_APP_VER = "app_version";
    DR_KEY_SYS_VER = "sys_version";
    DR_KEY_MAC_ADDR = "mac_addr";
    DR_KEY_EVT_COMM = "evt_comm";
    DR_KEY_DAU_MODULE_ID = "event_id";
    DR_KEY_DAU_ERR_CODE = "err_code";
    DR_KEY_DAU_ERR_INFO = "err_info";
    DR_KEY_DAU_EXT = "ext";
    DR_KEY_UPLAOD_EVENT_ID = "event_id";
    DR_KEY_UPLAOD_ERR_CODE = "err_code";
    DR_KEY_UPLAOD_ERR_INFO = "err_info";
    DR_KEY_UPLOAD_FILE_SIZE = "file_size";
    DR_KEY_UPLOAD_UP_USE_TIME = "up_usetime";
    DR_KEY_UPLOAD_UP_ip = "up_ip";
    COMMAND_ID_COMMENT_UGC_UPLOAD_40401 = "ugc_upload";
    COMMAND_ID_COMMENT_DAU_49999 = "DAU";
    DR_KEY_ERROR_CODE = "u32_error_code";
    DR_KEY_ERROR_MSG = "str_error_msg";
    DR_KEY_MSG_MORE = "str_msg_more";
    PEE_SERVER_DROP = 1000;
    PEE_CONN_SERVER_FAILED = 1001;
    PEE_RECONN_BEGIN = 1002;
    PEE_DROP_FRAME = 2001;
    PEE_TURN_HWENCODE = 2002;
    PEE_ENCODE_INIT = 2003;
    PEE_ENCODE_FAIL = 2004;
    PEE_ENCODE_INIT_ANDROID = 2005;
    PEE_ENCODE_FAIL_ANDROID = 2006;
    PEE_QUIC_TO_TCP = 2007;
    PEE_QOS_RESULT = 2008;
    PEE_VIDEO_ENCODE_SW_TO_HW = 2009;
    COMMAND_ID_40001 = 40001;
    COMMAND_ID_40000 = 40000;
    COMMAND_ID_40002 = 40002;
    COMMAND_ID_40003 = 40003;
    COMMAND_ID_40101 = 40101;
    COMMAND_ID_40100 = 40100;
    COMMAND_ID_40102 = 40102;
    COMMAND_ID_40201 = 40201;
    COMMAND_ID_40200 = 40200;
    COMMAND_ID_40202 = 40202;
    COMMAND_ID_VOD_ACTION_DR = 40301;
    COMMAND_ID_UGC_UPLOAD = 40401;
    COMMAND_ID_LINKMIC = 40402;
    COMMAND_ID_DAU = 49999;
    MODULE_PPSERVER = 1000;
    MODULE_UPLOAD = 1001;
    MODULE_STREAM_PROCESS = 1002;
    MODULE_CONTROLLER = 1003;
    MODULE_PUSH_SDK = 1004;
    MODULE_PLAYER_SDK = 1005;
    MODULE_TEG_UPLOAD = 1006;
    MODULE_LIVE_CODEC = 1007;
    MODULE_DC = 1008;
    MODULE_CDN = 1009;
    MODULE_VOD_PLAYER_SDK = 1010;
    MODULE_VOD_ACTION_PLAYER_SDK = 1011;
    DR_DAU_EVENT_ID_LINK_MIC = 1001;
    DR_DAU_EVENT_ID_UGC_PUSH_RECORD = 1002;
    DR_DAU_EVENT_ID_UGC_PLAY_RECORD = 1003;
    DR_DAU_EVENT_ID_UGC_CUT = 1004;
    DR_DAU_EVENT_ID_UGC_JOIN = 1005;
    DR_DAU_EVENT_ID_UGC_PUBLISH = 1006;
    DR_DAU_EVENT_ID_REVERB = 1007;
    DR_DAU_EVENT_ID_BGM = 1008;
    DR_DAU_EVENT_ID_EYE_SCALE = 1009;
    DR_DAU_EVENT_ID_FACE_SCALE = 1010;
    DR_DAU_EVENT_ID_FILTER = 1011;
    DR_DAU_EVENT_ID_GREEN_SCREEN = 1012;
    DR_DAU_EVENT_ID_MOTION_TMPL = 1013;
    DR_DAU_EVENT_ID_SCREEN_CAPTURE = 1014;
    DR_DAU_EVENT_ID_VOD_PLAY = 1997;
    DR_DAU_EVENT_ID_LIVE_PLAY = 1998;
    DR_DAU_EVENT_ID_LIVE_PUSH = 1999;
  }
}


/* Location:              D:\tools\apktool\weixin6519android1140\jar\classes2-dex2jar.jar!\com\tencent\liteav\basic\datareport\TXCDRDef.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */